<?php
/* ===============================================================
	GET POST TYPES TO USE SEO
=============================================================== */
$devhelper_use_seo_on_get = str_replace(' ', '', devOpt('developer_seo_posttypes', false)); // Get Post Types
$devhelper_use_seo_on_get = explode(',', $devhelper_use_seo_on_get); // Make an Array With The Post Types

$devhelper_use_seo_on_get_cnt = 0;

/* -- Loop and make the array for ACF with the post types -- */
foreach( $devhelper_use_seo_on_get as $post_type ){
	$devhelper_use_seo_on[][] = array(
		'param' => 'post_type',
		'operator' => '==',
		'value' => $post_type,
		'order_no' => 0,
		'group_no' => $devhelper_use_seo_on_get_cnt,
	);

	$devhelper_use_seo_on_get_cnt++;
}



/* ===============================================================
	PAGE TITLE
=============================================================== */
add_filter('wp_title', 'devhelper_title', 1, 3);
function devhelper_title($title, $sep, $seplocation){
	global $post, $devhelper_title;

	/* ----- Get Title Configs ----- */
	$devhelper_title['sep'] = $sep;
	$devhelper_title['seplocation'] = $seplocation;

	/* ----- Get Site Name ----- */
	$title .= get_bloginfo('name');

	/* ----- Get Current Post ----- */
	$post_id    = $post->ID;
	$post_seo   = get_field( 'devhelper_seo_enable', $post_id );
	$global_seo = devOpt('active_seo', false);

	/* ----- Force the Post/Page Title ----- */
	if( $global_seo == 'yes' AND $post_seo == 'yes' AND str_replace(' ', '', get_field('devhelper_seo_title', $post_id)) != '' ){ // Force title
		$title = get_field('devhelper_seo_title', $post_id);
	/* ----- Don't force the Post/Page Title ----- */
	}else{
		return $title;
	}

	/* -- Return Value -- */
	return $title;
}

function get_devhelper_title($string){
	global $devhelper_title;
	if( $string == 'sep' ){
		return $devhelper_title['sep'];
	}else{
		return $devhelper_title['seplocation'];
	}
}



/* ===============================================================
	CONFIG FIELDS
=============================================================== */
add_action('wp_head', 'devhelper_seo', 2);
function devhelper_seo(){
	global $post, $devhelper_use_seo_on_get;
	

	/* -- Get Post ID & Post Type -- */
	$post_id   = $post->ID;
	$post_type = get_post( $post_id );
	$post_type = $post_type->post_type;


	/* -- Active SEO Global -- */
	if( devOpt('active_seo', false) == 'yes' ){

		/* -- Google: Author/Publisher -- */
		if( str_replace(' ', '', devOpt('developer_seo_google', false)) != '' ){
			$devhelper_seo['google']['author'] = "\n<link rel=\"author\" href=\"".devOpt('developer_seo_google', false)."\">";
			$devhelper_seo['google']['publisher'] = "\n<link rel=\"publisher\" href=\"".devOpt('developer_seo_google', false)."\">";
		}else{
			$devhelper_seo['google']['author'] = '';
			$devhelper_seo['google']['publisher'] = '';
		}

		/* -- Google: Webmasters -- */
		if( str_replace(' ', '', devOpt('developer_seo_google_webmasters', false)) != '' ){
			$devhelper_seo['google']['webmasters'] = "\n<meta name=\"google-site-verification\" content=\"".devOpt('developer_seo_google_webmasters', false)."\">";
		}else{
			$devhelper_seo['google']['webmasters'] = '';
		}

		/* -- Generated By Dev Helper -- */
		echo "\n\n<!-- SEO By Dev Helper Framework(getwpstarter.com) -->\n";

		/* -- Google -- */
		echo $devhelper_seo['google']['author'];
		echo $devhelper_seo['google']['publisher'];
		echo $devhelper_seo['google']['webmasters'];

		/* ############################################ */

		/* -- Active for This Post Type and SEO On Current PAGE -- */
		if( get_field('devhelper_seo_enable', $post_id) == 'yes' AND in_array($post_type, $devhelper_use_seo_on_get) ){

			/* -- Meta: Description -- */
			if( str_replace(' ', '', get_field('devhelper_seo_meta_description', $post_id)) != '' ){ 
				$devhelper_seo['meta']['description'] = "\n<meta name=\"description\" content=\"".get_field('devhelper_seo_meta_description')."\">";
			}else{
				$devhelper_seo['meta']['description'] = '';
			}

			/* -- Social: Title -- */
			if( str_replace(' ', '', get_field('devhelper_seo_social_title', $post_id)) != '' ){
				$devhelper_seo['social']['title']  = "\n<meta property=\"og:title\" content=\"".get_field('devhelper_seo_social_title', $post_id)."\">";
				$devhelper_seo['social2']['title'] = "\n\n<meta itemprop=\"name\" content=\"".get_field('devhelper_seo_social_title', $post_id)."\">";
			}else{
				$devhelper_seo['social']['title']  = "\n<meta property=\"og:title\" content=\"".wp_title(get_devhelper_title('sep'), false, get_devhelper_title('seplocation'))."\">";
				$devhelper_seo['social2']['title'] = "\n\n<meta itemprop=\"name\" content=\"".wp_title(get_devhelper_title('sep'), false, get_devhelper_title('seplocation'))."\">";
			}

			/* -- Social: Description -- */
			if( str_replace(' ', '', get_field('devhelper_seo_social_description', $post_id)) != '' ){
				$devhelper_seo['social']['description']  = "\n<meta property=\"og:description\" content=\"".get_field('devhelper_seo_social_description', $post_id)."\">";
				$devhelper_seo['social2']['description'] = "\n<meta itemprop=\"description\" content=\"".get_field('devhelper_seo_social_description', $post_id)."\">";
			}else if( str_replace(' ', '', get_field('devhelper_seo_meta_description', $post_id)) != '' ){
				$devhelper_seo['social']['description']  = "\n<meta property=\"og:description\" content=\"".get_field('devhelper_seo_meta_description', $post_id)."\">";
				$devhelper_seo['social2']['description'] = "\n<meta itemprop=\"description\" content=\"".get_field('devhelper_seo_meta_description', $post_id)."\">";
			}else{
				$devhelper_seo['social']['description']  = '';
				$devhelper_seo['social2']['description'] = '';
			}

			/* -- Social: Publisher -- */
			if( str_replace(' ', '', devOpt('developer_seo_facebook', false)) != '' ){
				$devhelper_seo['social']['publisher'] = "\n<meta property=\"article:publisher\" content=\"".devOpt('developer_seo_facebook', false)."\">";
			}else{
				$devhelper_seo['social']['publisher'] = '';
			}

			/* -- Social: Image -- */
			if( str_replace(' ', '', get_field('devhelper_seo_social_image', $post_id)) != '' ){
				$social_image = thumb( get_field('devhelper_seo_social_image', $post_id), 300, 300, 2 );
				$social_image = thumb( get_field('devhelper_seo_social_image', $post_id), 300, 300, 2 );
				$devhelper_seo['social']['image']  = "\n<meta property=\"og:image\" content=\"".$social_image."\">";
				$devhelper_seo['social2']['image'] = "\n<meta itemprop=\"image\" content=\"".$social_image."\">";
			}else{
				$devhelper_seo['social']['image']  = '';
				$devhelper_seo['social2']['image'] = '';
			}

			/* ----- SHOW FIELDS ----- */
			/* -- Default Description -- */
			echo $devhelper_seo['meta']['description'];

			/* -- Social -- */
			echo "\n\n<meta property=\"og:locale\" content=\"".get_bloginfo('language')."\">";
			echo "\n<meta property=\"og:type\" content=\"website\">";
			echo $devhelper_seo['social']['title'];
			echo $devhelper_seo['social']['description'];
			echo "\n<meta property=\"og:url\" content=\"".get_bloginfo('url')."/\">";
			echo "\n<meta property=\"og:site_name\" content=\"".get_bloginfo('name')."\">";
			echo $devhelper_seo['social']['publisher'];
			echo $devhelper_seo['social']['image'];

			echo $devhelper_seo['social2']['title'];
			echo $devhelper_seo['social2']['description'];
			echo $devhelper_seo['social2']['image'];

		} // Active SEO On Page AND Active For This Post Type

		/* ############################################ */

		/* -- Generated By Dev Helper -- */
		echo "\n\n<!-- End Seo By Dev Helper Framework(getwpstarter.com) -->\n\n\n"; 

	} // Active SEO Global
}


?>