<?php
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_configuracoes-do-custom-post-type',
		'title' => __('Configurações do Custom Post Type', 'wpstarter'),
		'fields' => array (
			array (
				'key' => 'field_54128861377ec',
				'label' => __('Geral', 'wpstarter'),
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_54128b1975810',
				'label' => __('Post Slug', 'wpstarter'),
				'name' => 'post_slug',
				'type' => 'text',
				'instructions' => __("O campo é obrigatório.<br>
	Não use caracteres especiais.<br>
	Quando for fazer uma busca para este post você usará este slug.<br>
	<b>Exemplo se o slug for filmes:</b><br>
	<code>".'$sql_movies'." = new WP_Query( array('post_type'=>'filmes') );</code>", 'wpstarter'),
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5413069ff15a8',
				'label' => __('Nome (Singular)', 'wpstarter'),
				'name' => 'post_name_singular',
				'type' => 'text',
				'instructions' => __('O campo é obrigatório.<br><b>Exemplo:</b> Filme', 'wpstarter'),
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5413087d90dcf',
				'label' => __('Nome (Plural)', 'wpstarter'),
				'name' => 'post_name_plural',
				'type' => 'text',
				'instructions' => __('O campo é obrigatório.<br><b>Exemplo:</b> Filmes', 'wpstarter'),
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_541289b0377ee',
				'label' => __('Rótulos', 'wpstarter'),
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5416ce4f3deeb',
				'label' => __('Dica', 'wpstarter'),
				'name' => '',
				'type' => 'message',
				'message' => __('Tirando o rótulo <b>Nome no Menu</b> todos eles já tem um valor predefinido. Caso queira você pode alterá-los, porém, não é preciso. De qualquer forma dê uma lida nos rótulos que construímos para o seu post type.', 'wpstarter'),
			),
			array (
				'key' => 'field_5413094346cd9',
				'label' => __('Nome no Menu', 'wpstarter'),
				'name' => 'post_menu',
				'type' => 'text',
				'instructions' => __('Campo obrigatório.<br><b>Exemplo:</b> Filmes', 'wpstarter'),
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54130c45af553',
				'label' => __('Adicionar Novo', 'wpstarter'),
				'name' => 'post_add_new',
				'type' => 'text',
				'instructions' => __('O campo é obrigatório.<br><b>Exemplo:</b> Adicionar Novo', 'wpstarter'),
				'required' => 1,
				'default_value' => __('Adicionar Novo', 'wpstarter'),
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54130a7dd2b36',
				'label' => __('Adicionar Novo Item', 'wpstarter'),
				'name' => 'post_add_new_item',
				'type' => 'text',
				'instructions' => __('O campo é obrigatório.<br><b>Exemplo:</b> Adicionar Novo Item', 'wpstarter'),
				'required' => 1,
				'default_value' => __('Adicionar Novo Item', 'wpstarter'),
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54130dbdec2c2',
				'label' => __('Editar Item', 'wpstarter'),
				'name' => 'post_edit_item',
				'type' => 'text',
				'instructions' => __('O campo é obrigatório.<br><b>Exemplo:</b> Editar Item', 'wpstarter'),
				'required' => 1,
				'default_value' => __('Editar Item', 'wpstarter'),
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54130e2e02eba',
				'label' => __('Atualizar Item', 'wpstarter'),
				'name' => 'post_update_item',
				'type' => 'text',
				'instructions' => __('O campo é obrigatório.<br><b>Exemplo:</b> Atualizar Item', 'wpstarter'),
				'required' => 1,
				'default_value' => __('Atualizar Item', 'wpstarter'),
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54130dfb02eb9',
				'label' => __('Ver Item', 'wpstarter'),
				'name' => 'post_view_item',
				'type' => 'text',
				'instructions' => __('O campo é obrigatório.<br><b>Exemplo:</b> Ver Item', 'wpstarter'),
				'required' => 1,
				'default_value' => __('Ver Item', 'wpstarter'),
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54130b30d2b37',
				'label' => __('Buscar Item', 'wpstarter'),
				'name' => 'post_search',
				'type' => 'text',
				'instructions' => __('O campo é obrigatório.<br><b>Exemplo:</b> Buscar Item', 'wpstarter'),
				'required' => 1,
				'default_value' => __('Buscar Item', 'wpstarter'),
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54130c16af552',
				'label' => __('Todos Itens', 'wpstarter'),
				'name' => 'post_all_items',
				'type' => 'text',
				'instructions' => __('O campo é obrigatório.<br><b>Exemplo:</b> Todos os Itens', 'wpstarter'),
				'required' => 1,
				'default_value' => __('Todos os Itens', 'wpstarter'),
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54130d3569e52',
				'label' => __('Não Encontrado', 'wpstarter'),
				'name' => 'post_not_found',
				'type' => 'text',
				'instructions' => __('O campo é obrigatório.<br><b>Exemplo:</b> Não encontrado', 'wpstarter'),
				'required' => 1,
				'default_value' => __('Não encontrado', 'wpstarter'),
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54130ea4e4979',
				'label' => __('Não Encontrado na Lixeira', 'wpstarter'),
				'name' => 'post_not_found_in_trash',
				'type' => 'text',
				'instructions' => __('O campo é obrigatório.<br><b>Exemplo:</b> Nada encontrado na lixeira.', 'wpstarter'),
				'required' => 1,
				'default_value' => __('Nada encontrado na lixeira', 'wpstarter'),
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5412898b377ed',
				'label' => __('Opções', 'wpstarter'),
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5416c8d26f820',
				'label' => __('Suportes', 'wpstarter'),
				'name' => 'post_supports',
				'type' => 'checkbox',
				'instructions' => __('Selecione pelo menos um suporte. Recomendamos que sempre selecione o suporte <b>Title</b>.<br>
	Campos customizados podem ser adicionados ao post type indo na página <b>Desenvolvedor</b> e clicando em <b>Custom Fields</b>.<br>
	<b>Obs:</b> O suporte a títulos já é automaticamente adicionado.', 'wpstarter'),
				'choices' => array (
					'editor'          => __('Content (Editor)', 'wpstarter'),
					'excerpt'         => __('Excerpt', 'wpstarter'),
					'author'          => __('Author', 'wpstarter'),
					'thumbnail'       => __('Featured Image', 'wpstarter'),
					'comments'        => __('Comments', 'wpstarter'),
					'trackbacks'      => __('Trackbacks', 'wpstarter'),
					'revisions'       => __('Revisions', 'wpstarter'),
					'custom-fields'   => __('Custom Fields', 'wpstarter'),
					'page-attributes' => __('Page Attributes', 'wpstarter'),
				),
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_5416c9905d493',
				'label' => __('Excluir da Pesquisa', 'wpstarter'),
				'name' => 'post_exclude_search',
				'type' => 'select',
				'instructions' => __('Posts desse tipo devem ser excluídos dos resultados de pesquisa.', 'wpstarter'),
				'required' => 1,
				'choices' => array (
					'no'  => __('Não', 'wpstarter'),
					'yes' => __('Sim', 'wpstarter'),
				),
				'default_value' => 'no',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5416ca2813a15',
				'label' => __('Ativar Exportação', 'wpstarter'),
				'name' => 'post_export',
				'type' => 'select',
				'instructions' => __('Permite à exportação do post type.', 'wpstarter'),
				'required' => 1,
				'choices' => array (
					'yes' => __('Sim', 'wpstarter'),
					'no'  => __('Não', 'wpstarter'),
				),
				'default_value' => 'yes',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_541289d3377ef',
				'label' => __('Visibilidade', 'wpstarter'),
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5416ecaebd106',
				'label' => __('Mostrar na Barra do Admin', 'wpstarter'),
				'name' => 'post_admin_bar_display',
				'type' => 'select',
				'instructions' => __('Mostrar o post type na barra de administração do usuário atual.', 'wpstarter'),
				'required' => 1,
				'choices' => array (
					'yes' => __('Sim', 'wpstarter'),
					'no'  => __('Não', 'wpstarter'),
				),
				'default_value' => 'yes',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5416cb1013a17',
				'label' => __('Mostrar na Sidebar do Admin', 'wpstarter'),
				'name' => 'post_sidebar_display',
				'type' => 'select',
				'instructions' => __('Mostrar o post type na sidebar do painel de administração.', 'wpstarter'),
				'required' => 1,
				'choices' => array (
					'yes' => __('Sim', 'wpstarter'),
					'no'  => __('No', 'wpstarter'),
				),
				'default_value' => 'yes',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5416cb9c13a18',
				'label' => __('Posição na Sidebar', 'wpstarter'),
				'name' => 'post_sidebar_position',
				'type' => 'select',
				'instructions' => __('Escolha a posição do post type na sidebar do painel de administração.', 'wpstarter'),
				'required' => 1,
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5416cb1013a17',
							'operator' => '==',
							'value' => 'yes',
						),
					),
					'allorany' => 'all',
				),
				'choices' => array (
					5   => __('5 - below Posts', 'wpstarter'),
					10  => __('10 - below Posts', 'wpstarter'),
					15  => __('15 - below Links', 'wpstarter'),
					20  => __('20 - below Pages', 'wpstarter'),
					25  => __('25 - below Comments', 'wpstarter'),
					60  => __('60 - below first separator', 'wpstarter'),
					65  => __('65 - below Plugins', 'wpstarter'),
					70  => __('70 - below Users', 'wpstarter'),
					75  => __('75 - below Tools', 'wpstarter'),
					80  => __('80 - below Settings', 'wpstarter'),
					100 => __('100 - below second separator', 'wpstarter'),
				),
				'default_value' => 5,
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5416cd289f583',
				'label' => __('Permalinks', 'wpstarter'),
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5416cd409f584',
				'label' => __('Default Permalinks', 'wpstarter'),
				'name' => '',
				'type' => 'message',
				'message' => __('Os permalinks são montados com o valor que você inseriu em <b>Post Slug</b> na aba <b>Geral</b>.
	<b>Exemplo:</b> Se o post slug for filmes o permalink será http://meusite.com/filmes/post-exemplo', 'wpstarter'),
			),
			array (
				'key' => 'field_54128a1a377f0',
				'label' => __('Capacidade', 'wpstarter'),
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5416ccb1af809',
				'label' => __('Tipo de Capacidade Base', 'wpstarter'),
				'name' => 'post_capability',
				'type' => 'select',
				'instructions' => __('Utilizado como uma base para a construção de capacidades.', 'wpstarter'),
				'required' => 1,
				'choices' => array (
					'post' => __('Posts', 'wpstarter'),
					'page' => __('Pages', 'wpstarter'),
				),
				'default_value' => 'post',
				'allow_null' => 0,
				'multiple' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'customposttypes',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'the_content',
				2 => 'excerpt',
				3 => 'custom_fields',
				4 => 'discussion',
				5 => 'comments',
				6 => 'revisions',
				7 => 'slug',
				8 => 'author',
				9 => 'format',
				10 => 'featured_image',
				11 => 'categories',
				12 => 'tags',
				13 => 'send-trackbacks',
			),
		),
		'menu_order' => 1,
	));
}
?>